---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: "{{webpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on ubuntu
    service:

      name: "{{webpackonubuntu}}"
      state: restarted
    when: ansible_os_family=="Debian"

  - name: install webserver on redhat
    yum:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want to start webserver
    service:
      name: "{{mywebpackonredhat}}"
      state: started
    when: ansible_os_family=="RedHat"
    

